severity: 0
pipelines:
  - name: main
    sources:
      - type: random
        rate: 1.0
        range: [8, 8]
      - type: tcp
        endpoint: ["::", 50031]
    outputs:
      - type: stream
      - type: files
        path: /tmp/zenlog.log.0
        pattern: "{message}"
