severity: 0
pipeline:
  - name: zen
    sources:
      - type: random
        rate: 1.0
        range: [8, 8]
      - type: tcp
        endpoint: ["::", 50031]
    outputs:
      - type: stream
      - type: file
        path: /tmp/zenlog.log.0
